### ISSUE TITLE
Use USPS API + other GIS APIs to update 211 characteristics

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/data-architecture#194]
## Goal

Chicago is home to over 120k small multi-family properties with 2-6 units. But for roughly 8.5k of them, according to our data, they have zero or or null units.

The goal of this issue is to test using USPS's API to obtain the count of residential units and count of commercial units associated with each PIN's property location address. These unit counts will be provided to the Valuations department for verification and, if deemed valid, will change the property's characteristics in iasWorld. 

## Background

There are roughly 8,500 PINs in the City triad with a property class code 211 (Two to six residential apartments, any age) or 212 (Two to six mixed-use apartments, any age, up to 20,000 sq. ft.) but have "None" or "N/A" num_apartments in characteristics data. This may affect what the model learns about the real estate market for small multi-family homes, with downstream effects on what the model thinks the value is for these properties and properties like them. 

Furthermore, if the valuations department chooses to use the income approach to value these properties, knowing the number of units is very important. 

Most of these homes are in Lake Township (3.3k), then West Chicago Township, (2.8k), then Hyde Park Township, (1.5k), then Jefferson and South Chicago Townships (<500 each).

## Tasks

- [ ] **Identify the universe of PINs** in the City try with class 211 or 212 and null or no num_apartments in the most recent tax year. Retrieve their property location addresses, the number of cards (improvements) on the PIN, and the class of each card. 
- [ ] **Identify an approach to query the USPS Address Verification API using property location address, query different unit IDs, and track the number of distinct residential and/or commercial units.** The approach should take into account that property location address is not always USPS compliant, and should track when this happens. The approach should also take into account that some of these addresses might actually have 0 units, and should track when this happens.
  - There is also an internal county GIS address API that we may be able to use for the same task
- [ ] **Time permitting:** Create a flat file of this universe that will help with outreach (specs below).
- [ ] **Time permitting:** Expand the universe to all tris, not just the City tri.
- [ ] **Time permitting:** What about changing the universe to those with num_apartments = Two? Six? This is a validation check of the approach. 

## Outputs

- [ ] A script (R or Python) included in a PR to close this issue, which performs the tasks outlined above. 
- [ ] A flat file for this universe of PINs. The file's columns should be: PIN, township name, class code, property location address, number of estimated residential units, number of estimated commercial units.

## Reach Goal

If time allows, let's produce other flat files that could help with outreach and assess the impact of this work. 

- [ ] Stretch goal \#1: Outreach. Add to the flat file the following columns. Number of cards, lon, lat, Ward number, Chicago community area name, most recent sale date, most recent sale price. 
- [ ] Stretch goal #2: Map. If desired by Assessor Leadership / Outreach team, create a map using the flat file produced by Stretch Goal #1. 
- [ ] Stretch goal #3: Did it work? After Valuations' review, use the same universe to pull the current number of units.

**Comment by Damonamajor** [comment]
Bellow are the results from a first pass at querying the internal [GIS ](https://gisinternal.cookcountyil.gov/geoenrichment/rest/services/USA_Geocoder_2023/GeocodeServer/findAddressCandidates)database.


**Structure of Query**
Each of the 211 or 212 buildings with 0 apartments are queried. The following sub-addresses are appended, querying each address 33 times. The sub-addresses represent four sub-categories, numbers, letters, combination of numbers and letters, and directions. 

 "1","2", "3", "4", "5", "6", "A", "B", "C", "D", "E", "F", "1a", "1b", "1c", "2a", "2b", "2c", "3a", "3b", "3c", "1E", "1W", "2E", "2W", "3E", "3W", "1N", "1S", "2N", "2S", "3N", "3S"

**Table of Sub-Address Apartment Counts**

0 | 1 | 2 | 3 | 4 | 5 | 6 | >6
-- | -- | -- | -- | -- | -- | -- | --
3641 | 1535 | 2408 | 498 | 208 | 70 | 47 | 93

**Interpreting Table**

- Results with 0 receive no responses. This means that including the sub-address made the observation invalid. For example 200 South Street could be a valid address, but 200 South Street Apt1 is not a valid address.
- Results with 1 are most often caused by Apt1 being considered valid, but no other addresses being considered valid. This does not match with our understanding of 211s and 212s.
- Results with > 6 were pinged for multiple categories. This could be for two reasons. 
-- Some observations included something like Apt1 in their base address. This meant that when the sub-address was appended it would be 200 South Street Apt 1 Apt 2. This lead to many addresses being read as just Apt 1 and being returned as positive. I did a bit of string cleaning to remove the most common errors (this occurred more than I expected). 
-- The second reason is that separate categories are being calculated as valid, for example Apt 1 and Apt A both return positive responses. This could be easily remedied with data cleaning. 


**Takeaway**
- Although I couldn't run the full test on USPS, it did seem as though the results are more comprehensive. I think that it is worth talking about how to access this data.
- While the internal GIS system can provide some information, I wouldn't feel confident including it in the model, mostly due to the number of observations which return 0. 
- It does seem like there is some potential of identifying the different numbers of apartments. For example, there are 2408 units with 2 addresses, while only 208 units with 4 addresses. 


**Next Steps** 
I am going to play around with including Apt 1 vs just 1 in the query, but this did not provide significant changes last time I did it. 

@dfsnow 
@ccao-jardine
