### ISSUE TITLE
Ensure Integrity of Buyer/Seller Information for  vw_pin_sale.sql

### ISSUE THREAD

**Issue by Damonamajor** [ccao-data/data-architecture#198]
When working through [Sale Data Quality Checks](https://github.com/ccao-data/enterprise-intelligence/issues/9), it was uncovered that buyer and seller name was complete in MyDec data, while incomplete for 2016 and 2020-2022 in IASworld. 

The initial assumption is that iasWorld did not record a subset of data for particular years, but the expected modification did not fix the ingest.

This led to the _hypothesis_ that some information may be coded for the first parcel / card in each sale, meaning that depending on how data is sorted, incomplete buyer/seller name observations may be uploaded to vw_pin_sale.

**Tasks**

- [ ] Analyze how IASworld data is coded and identify the root-cause of integrity issues.
- [ ] If issues relate to incomplete observations being uploaded, identify if this extends to other variables.
- [ ] Update [vw_pin_sale.sql](https://github.com/ccao-data/data-architecture/blob/master/aws-athena/views/default-vw_pin_sale.sql) to ensure that complete data is ingested.
