### ISSUE TITLE
Create a new airport noise feature table using dbt

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/data-architecture#204]
**Due date:** 2023-11-09

Once #193 is merged, we need a way to "featurize" its outputs in a way that is useful for modeling. To that end, we should create a new SQL dbt model specifically for airport noise. The model should calculate the distance from each airport to each PIN, then transform that distance into the total DNL for each PIN. This _should_ be entirely possible using only SQL.

The final table should be located at `proximity.dist_pin_to_airport` and look something like:

| pin10 | dist_to_ohare | dist_to_midway | dnl_ohare | dnl_midway | dnl_total | year |
|-------|---------------|----------------|-----------|------------|-----------|------|
| 12345 | 5000          | 10000          | 15        | 5          | 70        | 2020 |
| 54321 | 10000         | 1000           | 5         | 20         | 75        | 2021 |

## To-dos

Complete the following checklist to add the model:

- [x] Write a SQL query that gets the distance from each airport to each PIN.
  You can copy one of the [existing proximity queries](https://github.com/ccao-data/data-architecture/blob/master/aws-athena/ctas/proximity-dist_pin_to_hospital.sql) and edit it
  to work for airports (remove the dbt configuration block at the top first).
  I recommend testing your query in the [Athena console](https://us-east-1.console.aws.amazon.com/athena/home?region=us-east-1) using a small subset of PINs.
  Also, it's totally okay in this case to simply hard-code the airport locations into the
  query, since they're unlikely to ever change, same with the regression coefficients.

- [x] Save the SQL query that creates the model in the appropriate subfolder
  of the `aws-athena/` directory. In this case, the SQL query should live at
  `data-architecture/aws-athena/ctas/proximity-dist_pin_to_airport.sql`.
  Use the dbt functions [`source()`](https://docs.getdbt.com/reference/dbt-jinja-functions/source) and [`ref()`](https://docs.getdbt.com/reference/dbt-jinja-functions/ref) to
  reference other models where possible in your query.

```sql
-- View or table example
-- Either aws-athena/views/default-vw_new_model.sql
-- or aws-athena/ctas/default-new_model.sql
select pin10, year
from {{ source('raw', 'foobar') }}
join {{ ref('default.vw_pin_universe') }}
using (pin10, year)
```

- [x] Configure model materialization. You'll need to add a config block
  to the top of the SQL query to configure materialization. This will
  tell dbt to save your query results as a new table.

```sql
-- Table example
-- aws-athena/ctas/default-new_model.sql
{{
  config(
    materialized='table',
    partitioned_by=['year'],
    bucketed_by=['pin10'],
    bucket_count=1
  )
}}
select pin10, year
from {{ source('raw', 'foobar') }}
join {{ ref('default.vw_pin_universe') }}
using (pin10, year)
```

- [x] Add a symlink from the appropriate subfolder of the `dbt/models/`
  directory to the SQL query you created in the `aws-athena/` directory.
  Note that the path for the target file in the `aws-athena/` directory
  needs to be relative to the location of the symlink, _not_ to the
  location of the working directory where you run the `ln` command;
  as a result, the path to the target file in the `aws-athena/` directory
  will not autocomplete in your shell as it usually does when you use
  the tab key.

```bash
# View example
ln -s ../../../aws-athena/views/default-vw_new_model.sql dbt/models/default/default.vw_new_model.sql

# Table example
ln -s ../../../aws-athena/ctas/default-new_model.sql dbt/models/default/default.new_model.sql
```

- [x] The `ln` command won't raise an error if the link it creates is invalid,
  so use `cat` to confirm that the link is pointing to the correct file.

```bash
# View example
cat dbt/models/default/default.vw_new_model.sql

# Table example
cat dbt/models/default/default.new_model.sql
```

- [x] Update the `schema.yml` file in the subfolder of `dbt/models/` where you
  created your symlink to add a definition for your model. Make sure to add
  descriptions for new entities (models, sources, columns, etc). See
  [Model description](/ccao-data/data-architecture/tree/master/dbt#model-description)
  and [Column descriptions](/ccao-data/data-architecture/tree/master/dbt#column-descriptions)
  for specific guidance on doc locations and using docs blocks

```diff
# Table example (only the model name would change for a view)
--- a/dbt/models/default/schema.yml
+++ b/dbt/models/default/schema.yml

 models:
+  - name: default.new_model
+    description: New model
+    columns:
+      - name: pin10
+        description: 10-digit PIN
+      - name: year
+        description: Year
   - name: default.vw_pin_history
     description: PIN history
     tests:
```

- [x] Commit your changes to a branch and open a pull request to build your
  model and run tests in a CI environment.
