### ISSUE TITLE
Add GitHub Action to check dbt YAML key sort order

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/data-architecture#209]
Now that our dbt documentation is largely finished, it's critical that we keep it organized and up-to-date. To ease in organization and maintenance of the the documentation files, I propose we add a quick GitHub Actions workflow that checks the sorting of certain dbt arrays and markdown headers.

Specifically, we should check the that all array keys in the `columns:` and `tests:` items are _sorted alphabetically_. These items are located in each database's `schema.yml` file or the specific table `.yml` file for databases broken out by table.

We should also check that each `docs.md`, `columns.md`, and `shared_columnd.md` file has alphabetically sorted markdown headings.

## Tasks

- [x] Create a Python script to check the sort order of `columns:` and `tests:` array items. Can likely use PyYAML for this pretty easily.
- [ ] Create a Python script to check the sort order of `docs.md`, `columns.md`, and `shared_columns.md`. 
- [x] Create a GitHub Actions workflow to run both scripts.
- [x] Alphabetize any incorrect array keys or markdown headings.
- [x] Update the dbt README with alphabetization rules.
