### ISSUE TITLE
Ingest Distressed Communities Index (DCI) for modeling

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/data-architecture#450]
## Overview

The Economic Innovation Group (EIG) calculates a census tract-level [Distressed Communities Index, or DCI](https://eig.org/distressed-communities/?regions%5B0%5D=60609&geo=zctas&lat=41.81&lon=-87.66&z=9.18). This might be a useful feature to include in the residential and condo AVMs. We should ingest the feature, add it to the warehouse, and then test it in the model.

## Task

- [x] Write an R or Python script to ingest the raw data from the linked site and place it in the raw S3 bucket
- [x] Write a Python model to ingest the data from the raw bucket, transform it, then write it to the warehouse S3 bucket
- [ ] Add the table resulting from the Python model to the appropriate Athena views. To figure out where it needs to be added, you can look at the lineage graph in dbt. Look at the model views to find everything upstream
- [ ] Update the dbt schema and documentation files for all view/table edits in Athena

Be sure to document this process along the way for https://github.com/ccao-data/wiki/issues/36.
